before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    binary: stub-server
    goos:
      - linux
      - darwin
      - windows
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'